### ISSUE TITLE
Applications force-killed by the manufacturer's Android

### ISSUE THREAD

**Issue by christophehenry** [UnifiedPush/android-connector#60]
The current message distribution system relies on Android's `BroadcastReceiver` and registering only the application package name. The causes problems if the target app (the one that should receive a notification from the UP implementor) has not been started, has been manually killed or has been reclaimed by the system. Then, there's no way, using  `BroadcastReceiver`s and `Context.sendBroadcast()`, to bring an application back to life, which defeats a bit the pupose of UP.

The protocol should rely on a system that is able to start an app, whether is exists in memory or not. The only system I can think of, is creating a dedicating an empty activity for that, registering that activity (instead of the application package name) and start it whenever a UP implementor should distribute a notification, using `Context.startActivity()`. This is how Android's sharing system works.

**Comment by p1gp1g** [comment]
You should check that website : https://dontkillmyapp.com/

Do you see solutions for your device ? Do you see improvement if you do what's recommended ?

**Comment by christophehenry** [comment]
I run Lineage. There shouldn't be any optimization beyond what's on AOSP. I guess there's not good solution. Maybe future Android API level come with a solution to ensure an app correctly receives notifications.

**Comment by p1gp1g** [comment]
Lineage uses some vendor blobs, I don't know if some on your device can be related to battery optimization :thinking: .

I wonder if the issue doesn't occur after the message is received by the application: have you disabled battery optimization for element for instance ? If the app is in background for a while, the sync with the server can takes time (it will be shorten with matrix sync v3) and the app may be killed during this process.

**Comment by christophehenry** [comment]
I just disabled battery optimizations. I'll see if it solves the problem. But honestly, I just wished users wouldn't have to do such configurations. Using a phone should be simple…
