### ISSUE TITLE
Publish this library to maven central

### ISSUE THREAD

**Issue by tehcneko** [UnifiedPush/android-connector#79]
https://central.sonatype.org/publish/publish-guide/

**Comment by connyduck** [comment]
I also found this guide super helpful for my own libraries https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/

**Comment by p1gp1g** [comment]
Thanks, that something that should be done

**Comment by p1gp1g** [comment]
https://central.sonatype.com/artifact/org.unifiedpush.android/connector done !
