### ISSUE TITLE
Docs say five methods to override, there are only four

### ISSUE THREAD

**Issue by nikclayton** [UnifiedPush/android-connector#84]
The docs say there are five methods to override in the receiver, there are only four.

https://github.com/UnifiedPush/documentation/compare/main...nikclayton:documentation-1:patch-1?expand=1 is the patch. I can't send this as a PR (or open an issue in the documentation repository) as the documentation repository has been limited to collaborators only.

**Comment by p1gp1g** [comment]
Good catch. The code is being migrated to codeberg: https://codeberg.org/UnifiedPush/documentation/

I can do the change directly if you prefer, or wait for a PR there ?

**Comment by p1gp1g** [comment]
btw, this repo is moved to codeberg too : https://codeberg.org/UnifiedPush/android-connector

**Comment by p1gp1g** [comment]
Done
